In [2]:
import numpy as np

In [3]:
a = np.array([3,8,2,67,45])

In [4]:
a

array([ 3,  8,  2, 67, 45])

In [5]:
print(a.size)
print(a.shape)
print(a.dtype)
print(len(a))

5
(5,)
int32
5


In [6]:
# create two D data
b = np.array([[10,11,13,14],[45,22,9,2],[6,5,1,8]])

In [7]:
print("Array is :")
print(b)
print("shape is :", b.shape)
print("size is :",b.size)
print("data type is :",a.dtype)
print("length is :",len(b))
print("Type is :",type(b))

Array is :
[[10 11 13 14]
 [45 22  9  2]
 [ 6  5  1  8]]
shape is : (3, 4)
size is : 12
data type is : int32
length is : 3
Type is : <class 'numpy.ndarray'>


In [8]:
# Array Operation
# 1. Item Accessing: Indexing: Subscripting: Slicing
# 2. Item Insertion
# 3. Item Deletion
# 4. Arithmatic

In [27]:
c = np.array([[[10,100], [11,13],[13,130],[14,140], 
               [45,145],[22,122],[9,19],[2,12],
               [6,16],[5,15],[1,11],[8,18]]])
print(c)

[[[ 10 100]
  [ 11  13]
  [ 13 130]
  [ 14 140]
  [ 45 145]
  [ 22 122]
  [  9  19]
  [  2  12]
  [  6  16]
  [  5  15]
  [  1  11]
  [  8  18]]]


In [28]:
print(c.ndim)

3


In [29]:
# Do subsripting
c[0,0]

array([ 10, 100])

In [30]:
c[:, -2]

array([[ 1, 11]])

In [31]:
c.shape

(1, 12, 2)

In [32]:
c[:, -2: -1]

array([[[ 1, 11]]])

In [35]:
c[0,1]

array([11, 13])

In [36]:
b[:,-2:-1]

array([[13],
       [ 9],
       [ 1]])

In [37]:
b

array([[10, 11, 13, 14],
       [45, 22,  9,  2],
       [ 6,  5,  1,  8]])

In [41]:
b[2,:]

array([6, 5, 1, 8])

In [42]:
b[2,:].ndim

1

In [45]:
b[2,:].shape

(4,)

In [46]:
print(b[-1:,:])
print(c[:1, :2, :1])
print(c[:, 1:2, :1])
print(c[-2:, -1:, :1])
print(c[:2, -2:, :])

[[6 5 1 8]]
[[[10]
  [11]]]
[[[11]]]
[[[8]]]
[[[ 1 11]
  [ 8 18]]]


In [47]:
# Item assignment
b[1,2] = 90
b 

array([[10, 11, 13, 14],
       [45, 22, 90,  2],
       [ 6,  5,  1,  8]])

In [48]:
# Item Insertion
a

array([ 3,  8,  2, 67, 45])

In [51]:
a =np.append(a, 80)
a

array([ 3,  8,  2, 67, 45, 80, 80])

In [53]:
np.append(b, [[9,90,900,9000]], axis = 0)

array([[  10,   11,   13,   14],
       [  45,   22,   90,    2],
       [   6,    5,    1,    8],
       [   9,   90,  900, 9000]])

In [54]:
np.append(b, [[9],[90],[900]], axis = 1)

array([[ 10,  11,  13,  14,   9],
       [ 45,  22,  90,   2,  90],
       [  6,   5,   1,   8, 900]])