In [1]:
import numpy as np

In [2]:
a = np.array([3,8,2,67,45])

In [3]:
a

array([ 3,  8,  2, 67, 45])

In [7]:
print(a.size)
print(a.shape)
print(a.dtype)
print(len(a))

5
(5,)
int32
5


In [8]:
# create two D data
b = np.array([[10,11,13,14],[45,22,9,2],[6,5,1,8]])

In [12]:
print("Array is :")
print(b)
print("shape is :", b.shape)
print("size is :",b.size)
print("data type is :",a.dtype)
print("length is :",len(b))
print("Type is :",type(b))

Array is :
[[10 11 13 14]
 [45 22  9  2]
 [ 6  5  1  8]]
shape is : (3, 4)
size is : 12
data type is : int32
length is : 3
Type is : <class 'numpy.ndarray'>


In [11]:
# Array Operation
# 1. Item Accessing: Indexing: Subscripting: Slicing
# 2. Item Insertion
# 3. Item Deletion
# 4. Arithmatic

[[10 11 13 14]
 [45 22  9  2]
 [ 6  5  1  8]]
